apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tbscs.abriment.dev
spec:
  conversion:
    strategy: None
  group: abriment.dev
  names:
    kind: TimeBasedScalingController
    listKind: TimeBasedScalingControllerList
    plural: tbscs
    shortNames:
    - tbsc
    singular: tbsc
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.schedulingConfig[*].startTime
      name: startTime
      type: string
    - jsonPath: .spec.schedulingConfig[*].endTime
      name: endTime
      type: string
    - jsonPath: .spec.schedulingConfig[*].replicas
      name: replicas
      type: integer
    - jsonPath: .spec.schedulingConfig[*].timeZone
      name: timeZone
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              defaultReplicas:
                default: 1
                format: int32
                minimum: 0
                type: integer
              schedulingConfig:
                items:
                  properties:
                    endTime:
                      description: End time of scaling in HH format.
                      pattern: ^([0-1]?[0-9]|2[0-3])$
                      type: string
                    replicas:
                      description: Number of replicas to scale to.
                      format: int32
                      minimum: 0
                      type: integer
                    startTime:
                      description: Start time of scaling in HH format.
                      pattern: ^([0-1]?[0-9]|2[0-3])$
                      type: string
                    timeZone:
                      default: Etc/UTC
                      description: The timezone, Defaults to UTC.
                      pattern: ^[A-Za-z]+/[A-Za-z_]+$
                      type: string
                  required:
                  - startTime
                  - endTime
                  - replicas
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
